### ISSUE TITLE
ES6 syntax fails in the simplest examples

### ISSUE THREAD

**Issue by SoonDead** [darlesson/atom-jsx-transform#1]
I have copied an example from https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

```
class HelloMessage extends React.Component {
   render() {
     return <div>Hello {this.props.name}</div>;
  }
}

React.render(<HelloMessage name="Sebastian" />, mountNode);
```

The result is missing it's first line:

```
  render() {
    return React.createElement("div", null, "Hello ", this.props.name);
  }
}

React.render(React.createElement(HelloMessage, {name: "Sebastian"}), mountNode);
```

**Comment by darlesson** [comment]
@SoonDead I will look into it. I imagine it is related to "Compile Without Notation" feature. You can find that in the settings.

**Comment by darlesson** [comment]
The workaround is to check "Compile Without Notation".

![image](https://cloud.githubusercontent.com/assets/174226/8535932/6137e84c-23ff-11e5-8da8-40fe895b2f8d.png)

I am working on the issue though.

**Comment by AddictArts** [comment]
If you have an import you will get an error "Parse Error: Line 1: Illegal import declaration", took awhile to figure out what was creating the js file with the error in it.

**Comment by darlesson** [comment]
I haven't had any time to work on Atom related stuff. If anybody here wants to collaborate with this repository or fork and submit a "pull request", please let me know.

**Comment by chung-leong** [comment]
The first line goes missing too with regular, non-ES6 files when "Compile Without Notation" isn't checked.

**Comment by darlesson** [comment]
As Atom was sunset, this repository is no longer needed.

See https://github.blog/2022-06-08-sunsetting-atom/
