### ISSUE TITLE
Lost "React.render(" in compiled js

### ISSUE THREAD

**Issue by quangmach** [darlesson/atom-jsx-transform#2]
I tried to compiled the jsx file to js but the compiled file lost the started "React.render("

**Comment by darlesson** [comment]
Is React.render( in the very first line of the file? It seems to be the same issue as https://github.com/darlesson/atom-jsx-transform/issues/1.

Please take a look at it as it provides a workaround until this issue is fixed.

**Comment by quangmach** [comment]
Yes, only when it stands at the very first line, the issue occurred.

**Comment by micooz** [comment]
Following example lost the first line too when **Compile Without Notation** is not enabled:

```
(function(){ // will be lost
// React code here.
})();
```

**Comment by darlesson** [comment]
@Micooz, please try the workaround for the issue #1.
